import{a as S,S as q,i as n}from"./assets/vendor-B2xQfKYm.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))i(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const s of r.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&i(s)}).observe(document,{childList:!0,subtree:!0});function o(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function i(t){if(t.ep)return;t.ep=!0;const r=o(t);fetch(t.href,r)}})();const A="49764635-55321af1e157f58385cb56e9b",v="https://pixabay.com/api/",l={image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15};async function m(a,e){try{const o=await S.get(`${v}`,{params:{key:A,q:a,image_type:l.image_type,orientation:l.orientation,safesearch:l.safesearch,page:e,per_page:l.per_page}});return{data:o.data,hits:o.data.hits,totalPages:B(o),page:o.config.params.page}}catch(o){console.error("Error fetching data from Pixabay:",o)}finally{}}function B(a){return Math.ceil(a.data.totalHits/a.config.params.per_page)}const g=document.querySelector(".gallery"),p=document.querySelector(".loader"),y=document.querySelector(".load-more"),M=new q(".gallery a",{});async function f(a){try{const e=await a,o=e.hits.map(({webformatURL:i,largeImageURL:t,tags:r,likes:s,views:P,comments:_,downloads:w})=>`<li class="gallery-item">
                  <a href="${t}">
                    <img class="gallery-image" src="${i}" alt="${r}" />
                    <div class='item-footer'>
                      <p><b>likes</b> ${s}</p>
                      <p><b>views</b> ${P}</p>
                      <p><b>comments</b> ${_}</p>
                      <p><b>downloads</b> ${w}</p>
                    </div>
                  </a>
                </li>`).join("");g.insertAdjacentHTML("beforeend",o),M.refresh(),e.page===e.totalPages&&(L(),n.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight",timeout:2e3}))}catch(e){console.error("Error creating gallery:",e),n.error({message:"Something went wrong while creating the gallery.",position:"topRight",timeout:3e3})}}function E(){g.innerHTML=""}function h(){p.classList.remove("hidden-loader")}function b(){p.classList.add("hidden-loader")}function x(){y.classList.remove("load-more-hidden")}function L(){y.classList.add("load-more-hidden")}const u=document.querySelector(".form"),R=document.querySelector(".load-more");let c=null,d=null;u.addEventListener("submit",async a=>{if(a.preventDefault(),d=1,c=u.elements["search-text"].value.trim(),E(),c===""){n.error({message:"Please enter a search query!",position:"topRight",timeout:2e3});return}h();try{const e=await m(c,d);if(!e.data.hits.length){n.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",timeout:2e3}),L();return}f(e),x()}catch{n.error({message:"Error fetching data from Pixabay",position:"topCenter",timeout:3e3})}finally{b(),u.reset()}});R.addEventListener("click",$);async function $(){d+=1,document.querySelector(".gallery-item").getBoundingClientRect().height;const e=document.querySelector(".loader-wraper");document.querySelector(".gallery").insertAdjacentElement("afterend",e),h();try{const i=await m(c,d);f(i),requestAnimationFrame(()=>{const r=document.querySelector(".gallery-item").getBoundingClientRect().height;window.scrollBy({left:0,top:r*2,behavior:"smooth"})})}catch{n.error({message:"Error fetching data from Pixabay",position:"topCenter",timeout:3e3})}finally{b()}}
//# sourceMappingURL=index.js.map
