import{a as A,S,i as s}from"./assets/vendor-B2xQfKYm.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&n(i)}).observe(document,{childList:!0,subtree:!0});function o(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(e){if(e.ep)return;e.ep=!0;const r=o(e);fetch(e.href,r)}})();const v="49764635-55321af1e157f58385cb56e9b",q="https://pixabay.com/api/",l={image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15};async function m(a,t){try{const o=await A.get(`${q}`,{params:{key:v,q:a,image_type:l.image_type,orientation:l.orientation,safesearch:l.safesearch,page:t,per_page:l.per_page}});return{data:o.data,hits:o.data.hits,totalPages:w(o),page:o.config.params.page}}catch(o){console.error("Error fetching data from Pixabay:",o)}finally{}}function w(a){return Math.ceil(a.data.totalHits/a.config.params.per_page)}const g=document.querySelector(".gallery"),p=document.querySelector(".loader"),f=document.querySelector(".load-more");async function y(a){try{const t=await a,o=t.hits.map(({webformatURL:n,largeImageURL:e,tags:r,likes:i,views:L,comments:P,downloads:_})=>`<li class="gallery-item">
                  <a href="${e}">
                    <img class="gallery-image" src="${n}" alt="${r}" />
                    <div class='item-footer'>
                      <p><b>likes</b> ${i}</p>
                      <p><b>views</b> ${L}</p>
                      <p><b>comments</b> ${P}</p>
                      <p><b>downloads</b> ${_}</p>
                    </div>
                  </a>
                </li>`).join("");g.insertAdjacentHTML("beforeend",o),t.page===t.totalPages&&(E(),s.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight",timeout:2e3})),x.refresh()}catch(t){console.error("Error creating gallery:",t)}}function B(){g.innerHTML=""}function h(){p.classList.remove("hidden-loader")}function b(){p.classList.add("hidden-loader")}function M(){f.classList.remove("load-more-hidden")}function E(){f.classList.add("load-more-hidden")}const x=new S(".gallery a",{}),u=document.querySelector(".form"),$=document.querySelector(".load-more");let c=null,d=null;u.addEventListener("submit",async a=>{if(a.preventDefault(),d=1,c=u.elements["search-text"].value,B(),c===""){s.error({message:"Please enter a search inputValue!",position:"topRight",timeout:2e3});return}h(),m(c,d).then(o=>{if(o.data.hits.length===0){s.error({message:"Sorry, there are no images matching your search inputValue. Please try again!",position:"topRight",timeout:2e3});return}y(o),M()}).catch(()=>{s.error({message:"Error fetching data from Pixabay",position:"topCenter",timeout:3e3})}).finally(()=>{b()}),u.reset()});$.addEventListener("click",I);async function I(){d+=1,document.querySelector(".gallery-item").getBoundingClientRect().height;const t=document.querySelector(".loader-wraper");document.querySelector(".gallery").insertAdjacentElement("afterend",t),h();try{const n=await m(c,d);y(n),requestAnimationFrame(()=>{const r=document.querySelector(".gallery-item").getBoundingClientRect().height;window.scrollBy({left:0,top:r*2,behavior:"smooth"})})}catch{s.error({message:"Error fetching data from Pixabay",position:"topCenter",timeout:3e3})}finally{b()}}
//# sourceMappingURL=index.js.map
